version: "3.4"

services:
  csvbase_postgres:
    image: postgres:12.9
    ports:
      - "7432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: csvbase
    networks:
      csvbase:
    volumes:
      - ./init-schemas.sql:/docker-entrypoint-initdb.d/init-schemas.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  csvbase_migrations:
    build:
      context: .
      target: migrations
    environment:
      CSVBASE_DB_URL: 'postgresql://postgres:password@csvbase_postgres:5432/csvbase'
    networks:
      csvbase:
    command: ["alembic", "upgrade", "head"]

  csvbase:
    build: .
    environment:
      CSVBASE_DB_URL: 'postgresql://postgres:password@csvbase_postgres:5432/csvbase'
    ports:
      - "6001:6001"
    networks:
      csvbase:
    depends_on:
      csvbase_postgres:
        condition: service_healthy
      csvbase_migrations:
        condition: service_completed_successfully


networks:
  csvbase:
    driver: bridge
