services:
  csvbase_postgres:
    image: postgres:13
    ports:
      - "7432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: csvbase
    networks:
      csvbase:
    volumes:
      - ./init-schemas.sql:/docker-entrypoint-initdb.d/init-schemas.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  csvbase_migrations:
    build:
      context: .
    environment:
      CSVBASE_TOML: |
        db_url = "postgresql://postgres:password@csvbase_postgres:5432/csvbase"
    networks:
      csvbase:
    command:
      /bin/bash -c "echo \"$$CSVBASE_TOML\" > ~/.csvbase.toml && alembic upgrade head"
    depends_on:
      csvbase_postgres:
        condition: service_healthy

  csvbase:
    build: .
    environment:
      CSVBASE_TOML: |
        db_url = "postgresql://postgres:password@csvbase_postgres:5432/csvbase"
    command:
      /bin/bash -c "echo \"$$CSVBASE_TOML\" > ~/.csvbase.toml && gunicorn 'csvbase.web.app:init_app()' -b :6001"
    ports:
      - "6001:6001"
    networks:
      csvbase:
    depends_on:
      csvbase_postgres:
        condition: service_healthy
      csvbase_migrations:
        condition: service_completed_successfully


networks:
  csvbase:
    driver: bridge
